INSERT INTO gen_region (name) VALUES ('Arusha');
INSERT INTO gen_region (name) VALUES ('Dar es Salaam');
INSERT INTO gen_region (name) VALUES ('Dodoma');
INSERT INTO gen_region (name) VALUES ('Geita');
INSERT INTO gen_region (name) VALUES ('Iringa');
INSERT INTO gen_region (name) VALUES ('Kagera');
INSERT INTO gen_region (name) VALUES ('Katavi');
INSERT INTO gen_region (name) VALUES ('Kigoma');
INSERT INTO gen_region (name) VALUES ('Kilimanjaro');
INSERT INTO gen_region (name) VALUES ('Lindi');
INSERT INTO gen_region (name) VALUES ('Manyara');
INSERT INTO gen_region (name) VALUES ('Mara');
INSERT INTO gen_region (name) VALUES ('Mbeya');
INSERT INTO gen_region (name) VALUES ('Morogoro');
INSERT INTO gen_region (name) VALUES ('Mtwara');
INSERT INTO gen_region (name) VALUES ('Mwanza');
INSERT INTO gen_region (name) VALUES ('Njombe');
INSERT INTO gen_region (name) VALUES ('Pemba Kaskazini');
INSERT INTO gen_region (name) VALUES ('Pemba Kusini');
INSERT INTO gen_region (name) VALUES ('Pwani');
INSERT INTO gen_region (name) VALUES ('Rukwa');
INSERT INTO gen_region (name) VALUES ('Ruvuma');
INSERT INTO gen_region (name) VALUES ('Shinyanga');
INSERT INTO gen_region (name) VALUES ('Simiyu');
INSERT INTO gen_region (name) VALUES ('Singida');
INSERT INTO gen_region (name) VALUES ('Songwe');
INSERT INTO gen_region (name) VALUES ('Tabora');
INSERT INTO gen_region (name) VALUES ('Tanga');
INSERT INTO gen_region (name) VALUES ('Unguja Kaskazini');
INSERT INTO gen_region (name) VALUES ('Unguja Mjini Magharibi');
INSERT INTO gen_region (name) VALUES ('Unguja Kusini');
